// 代码生成时间: 2025-08-12 04:42:43
@author: Your Name
@date: Today's Date
*/

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.io.FileOutputStream;
import java.io.IOException;

public class ExcelAutoGenerator {

    /*
    生成Excel表格
    @param title 表格标题
    @param headerRow 表头数据
    @param dataRows 数据行
    @return 生成的Excel文件名
    */
    public String generateExcel(String title, String[] headerRow, Object[][] dataRows) {
        try {
            // 创建新的Excel工作簿
            Workbook workbook = new XSSFWorkbook();

            // 创建新的工作表
            Sheet sheet = workbook.createSheet(title);

            // 创建表头行
            Row headerRowObj = sheet.createRow(0);
            for (int i = 0; i < headerRow.length; i++) {
                Cell cell = headerRowObj.createCell(i);
                cell.setCellValue(headerRow[i]);
            }

            // 填充数据行
            for (int i = 0; i < dataRows.length; i++) {
                Row dataRow = sheet.createRow(i + 1);
                for (int j = 0; j < dataRows[i].length; j++) {
                    Cell cell = dataRow.createCell(j);
                    cell.setCellValue(dataRows[i][j].toString());
                }
            }

            // 将工作簿写入文件
            FileOutputStream outputStream = new FileOutputStream("AutoGeneratedExcel.xlsx");
            workbook.write(outputStream);
            workbook.close();
            outputStream.close();

            return "AutoGeneratedExcel.xlsx";
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }

    public static void main(String[] args) {
        ExcelAutoGenerator generator = new ExcelAutoGenerator();

        // 表头
        String[] headerRow = {"Name", "Age", "Email"};

        // 数据行
        Object[][] dataRows = {
            {"John Doe", 30, "johndoe@example.com"},
            {"Jane Doe", 25, "janedoe@example.com"}
        };

        // 生成Excel文件
        String generatedExcel = generator.generateExcel("Test Excel", headerRow, dataRows);

        if (generatedExcel != null) {
            System.out.println("Excel file generated: " + generatedExcel);
        } else {
            System.out.println("Failed to generate Excel file.");
        }
    }
}